[2023-07-11T13:32:01.164+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-04T00:00:00+00:00 [queued]>
[2023-07-11T13:32:01.191+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-04T00:00:00+00:00 [queued]>
[2023-07-11T13:32:01.192+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:32:01.290+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-04 00:00:00+00:00
[2023-07-11T13:32:01.301+0000] {standard_task_runner.py:57} INFO - Started process 6199 to run task
[2023-07-11T13:32:01.318+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-04T00:00:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpv028juiy']
[2023-07-11T13:32:01.326+0000] {standard_task_runner.py:85} INFO - Job 101: Subtask create_file
[2023-07-11T13:32:01.609+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-04T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:32:01.778+0000] {abstractoperator.py:598} ERROR - Exception rendering Jinja template for task 'create_file', field 'bash_command'. Template: '/opt/***/dags/file/mon_script.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/file/mon_script.sh
[2023-07-11T13:32:01.786+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/file/mon_script.sh
[2023-07-11T13:32:01.816+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=exercice_1, task_id=create_file, execution_date=20230704T000000, start_date=20230711T133201, end_date=20230711T133201
[2023-07-11T13:32:01.889+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 101 for task create_file (/opt/airflow/dags/file/mon_script.sh; 6199)
[2023-07-11T13:32:01.918+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-11T13:32:02.028+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:42:00.769+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-04T00:00:00+00:00 [queued]>
[2023-07-11T13:42:00.811+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-04T00:00:00+00:00 [queued]>
[2023-07-11T13:42:00.815+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:42:00.987+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-04 00:00:00+00:00
[2023-07-11T13:42:01.009+0000] {standard_task_runner.py:57} INFO - Started process 6493 to run task
[2023-07-11T13:42:01.032+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-04T00:00:00+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmp7fv9biru']
[2023-07-11T13:42:01.037+0000] {standard_task_runner.py:85} INFO - Job 140: Subtask create_file
[2023-07-11T13:42:01.227+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-04T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:42:01.689+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-04T00:00:00+00:00'
[2023-07-11T13:42:01.696+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:42:01.698+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:42:01.741+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:42:01.797+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:42:01.963+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230704T000000, start_date=20230711T134200, end_date=20230711T134201
[2023-07-11T13:42:02.085+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:42:02.301+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:48:16.223+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-04T00:00:00+00:00 [queued]>
[2023-07-11T13:48:16.269+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-04T00:00:00+00:00 [queued]>
[2023-07-11T13:48:16.301+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:48:16.506+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-04 00:00:00+00:00
[2023-07-11T13:48:16.563+0000] {standard_task_runner.py:57} INFO - Started process 6681 to run task
[2023-07-11T13:48:16.609+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-04T00:00:00+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmp246dpy4h']
[2023-07-11T13:48:16.617+0000] {standard_task_runner.py:85} INFO - Job 162: Subtask create_file
[2023-07-11T13:48:16.890+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-04T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:48:17.183+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-04T00:00:00+00:00'
[2023-07-11T13:48:17.202+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:48:17.207+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:48:17.244+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:48:17.299+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:48:17.414+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230704T000000, start_date=20230711T134816, end_date=20230711T134817
[2023-07-11T13:48:17.536+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:48:17.683+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:51:15.397+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-04T00:00:00+00:00 [queued]>
[2023-07-11T13:51:15.469+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-04T00:00:00+00:00 [queued]>
[2023-07-11T13:51:15.477+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:51:15.592+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-04 00:00:00+00:00
[2023-07-11T13:51:15.609+0000] {standard_task_runner.py:57} INFO - Started process 6803 to run task
[2023-07-11T13:51:15.619+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-04T00:00:00+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpj_xcw7dv']
[2023-07-11T13:51:15.629+0000] {standard_task_runner.py:85} INFO - Job 184: Subtask create_file
[2023-07-11T13:51:15.877+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-04T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:51:16.279+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-04T00:00:00+00:00'
[2023-07-11T13:51:16.287+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:51:16.288+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:51:16.341+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:51:16.382+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:51:16.493+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230704T000000, start_date=20230711T135115, end_date=20230711T135116
[2023-07-11T13:51:16.744+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:51:16.870+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:53:36.682+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-04T00:00:00+00:00 [queued]>
[2023-07-11T13:53:36.731+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-04T00:00:00+00:00 [queued]>
[2023-07-11T13:53:36.738+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:53:37.074+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-04 00:00:00+00:00
[2023-07-11T13:53:37.085+0000] {standard_task_runner.py:57} INFO - Started process 6926 to run task
[2023-07-11T13:53:37.100+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-04T00:00:00+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpq6pon2t2']
[2023-07-11T13:53:37.106+0000] {standard_task_runner.py:85} INFO - Job 206: Subtask create_file
[2023-07-11T13:53:37.267+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-04T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:53:37.517+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-04T00:00:00+00:00'
[2023-07-11T13:53:37.526+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:53:37.528+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:53:37.550+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:53:37.581+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:53:37.671+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230704T000000, start_date=20230711T135336, end_date=20230711T135337
[2023-07-11T13:53:37.761+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:53:37.894+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
