[2023-07-11T13:32:03.989+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-10T00:00:00+00:00 [queued]>
[2023-07-11T13:32:04.006+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-10T00:00:00+00:00 [queued]>
[2023-07-11T13:32:04.007+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:32:04.036+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-10 00:00:00+00:00
[2023-07-11T13:32:04.046+0000] {standard_task_runner.py:57} INFO - Started process 6205 to run task
[2023-07-11T13:32:04.053+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-10T00:00:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpegwo2anx']
[2023-07-11T13:32:04.058+0000] {standard_task_runner.py:85} INFO - Job 107: Subtask create_file
[2023-07-11T13:32:04.147+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-10T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:32:04.197+0000] {abstractoperator.py:598} ERROR - Exception rendering Jinja template for task 'create_file', field 'bash_command'. Template: '/opt/***/dags/file/mon_script.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/file/mon_script.sh
[2023-07-11T13:32:04.199+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/file/mon_script.sh
[2023-07-11T13:32:04.209+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=exercice_1, task_id=create_file, execution_date=20230710T000000, start_date=20230711T133203, end_date=20230711T133204
[2023-07-11T13:32:04.222+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 107 for task create_file (/opt/airflow/dags/file/mon_script.sh; 6205)
[2023-07-11T13:32:04.265+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-11T13:32:04.354+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:42:03.801+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-10T00:00:00+00:00 [queued]>
[2023-07-11T13:42:03.848+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-10T00:00:00+00:00 [queued]>
[2023-07-11T13:42:03.850+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:42:03.939+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-10 00:00:00+00:00
[2023-07-11T13:42:03.952+0000] {standard_task_runner.py:57} INFO - Started process 6520 to run task
[2023-07-11T13:42:03.971+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-10T00:00:00+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpoy0derps']
[2023-07-11T13:42:03.981+0000] {standard_task_runner.py:85} INFO - Job 146: Subtask create_file
[2023-07-11T13:42:04.191+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-10T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:42:04.473+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-10T00:00:00+00:00'
[2023-07-11T13:42:04.482+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:42:04.484+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:42:04.509+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:42:04.575+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:42:04.649+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230710T000000, start_date=20230711T134203, end_date=20230711T134204
[2023-07-11T13:42:04.747+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:42:04.813+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:48:20.229+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-10T00:00:00+00:00 [queued]>
[2023-07-11T13:48:20.290+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-10T00:00:00+00:00 [queued]>
[2023-07-11T13:48:20.291+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:48:20.397+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-10 00:00:00+00:00
[2023-07-11T13:48:20.410+0000] {standard_task_runner.py:57} INFO - Started process 6710 to run task
[2023-07-11T13:48:20.427+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-10T00:00:00+00:00', '--job-id', '168', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmp6enbocm7']
[2023-07-11T13:48:20.449+0000] {standard_task_runner.py:85} INFO - Job 168: Subtask create_file
[2023-07-11T13:48:20.702+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-10T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:48:21.094+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-10T00:00:00+00:00'
[2023-07-11T13:48:21.101+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:48:21.115+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:48:21.185+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:48:21.238+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:48:21.339+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230710T000000, start_date=20230711T134820, end_date=20230711T134821
[2023-07-11T13:48:21.446+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:48:21.530+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:51:19.536+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-10T00:00:00+00:00 [queued]>
[2023-07-11T13:51:19.559+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-10T00:00:00+00:00 [queued]>
[2023-07-11T13:51:19.560+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:51:19.610+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-10 00:00:00+00:00
[2023-07-11T13:51:19.629+0000] {standard_task_runner.py:57} INFO - Started process 6842 to run task
[2023-07-11T13:51:19.648+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-10T00:00:00+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpp081kh5d']
[2023-07-11T13:51:19.658+0000] {standard_task_runner.py:85} INFO - Job 191: Subtask create_file
[2023-07-11T13:51:19.910+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-10T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:51:20.403+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-10T00:00:00+00:00'
[2023-07-11T13:51:20.409+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:51:20.412+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:51:20.438+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:51:20.488+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:51:20.627+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230710T000000, start_date=20230711T135119, end_date=20230711T135120
[2023-07-11T13:51:20.751+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:51:20.889+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:53:39.504+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-10T00:00:00+00:00 [queued]>
[2023-07-11T13:53:39.537+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-10T00:00:00+00:00 [queued]>
[2023-07-11T13:53:39.542+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:53:39.637+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-10 00:00:00+00:00
[2023-07-11T13:53:39.655+0000] {standard_task_runner.py:57} INFO - Started process 6951 to run task
[2023-07-11T13:53:39.676+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-10T00:00:00+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpf7u2m42g']
[2023-07-11T13:53:39.682+0000] {standard_task_runner.py:85} INFO - Job 212: Subtask create_file
[2023-07-11T13:53:39.907+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-10T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:53:40.277+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-10T00:00:00+00:00'
[2023-07-11T13:53:40.282+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:53:40.295+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:53:40.333+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:53:40.400+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:53:40.460+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230710T000000, start_date=20230711T135339, end_date=20230711T135340
[2023-07-11T13:53:40.552+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:53:40.635+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
