[2023-07-11T13:32:02.226+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-06T00:00:00+00:00 [queued]>
[2023-07-11T13:32:02.245+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-06T00:00:00+00:00 [queued]>
[2023-07-11T13:32:02.249+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:32:02.287+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-06 00:00:00+00:00
[2023-07-11T13:32:02.306+0000] {standard_task_runner.py:57} INFO - Started process 6201 to run task
[2023-07-11T13:32:02.315+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-06T00:00:00+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmp32w8u7w3']
[2023-07-11T13:32:02.324+0000] {standard_task_runner.py:85} INFO - Job 103: Subtask create_file
[2023-07-11T13:32:02.446+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-06T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:32:02.556+0000] {abstractoperator.py:598} ERROR - Exception rendering Jinja template for task 'create_file', field 'bash_command'. Template: '/opt/***/dags/file/mon_script.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/file/mon_script.sh
[2023-07-11T13:32:02.572+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/file/mon_script.sh
[2023-07-11T13:32:02.598+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=exercice_1, task_id=create_file, execution_date=20230706T000000, start_date=20230711T133202, end_date=20230711T133202
[2023-07-11T13:32:02.627+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 103 for task create_file (/opt/airflow/dags/file/mon_script.sh; 6201)
[2023-07-11T13:32:02.698+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-11T13:32:02.850+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:42:01.781+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-06T00:00:00+00:00 [queued]>
[2023-07-11T13:42:01.845+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-06T00:00:00+00:00 [queued]>
[2023-07-11T13:42:01.865+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:42:01.945+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-06 00:00:00+00:00
[2023-07-11T13:42:01.963+0000] {standard_task_runner.py:57} INFO - Started process 6503 to run task
[2023-07-11T13:42:01.976+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-06T00:00:00+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpmy1vf7if']
[2023-07-11T13:42:01.983+0000] {standard_task_runner.py:85} INFO - Job 142: Subtask create_file
[2023-07-11T13:42:02.211+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-06T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:42:02.735+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-06T00:00:00+00:00'
[2023-07-11T13:42:02.746+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:42:02.765+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:42:02.792+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:42:02.840+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:42:02.960+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230706T000000, start_date=20230711T134201, end_date=20230711T134202
[2023-07-11T13:42:03.065+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:42:03.159+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:48:17.729+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-06T00:00:00+00:00 [queued]>
[2023-07-11T13:48:17.775+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-06T00:00:00+00:00 [queued]>
[2023-07-11T13:48:17.777+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:48:17.892+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-06 00:00:00+00:00
[2023-07-11T13:48:17.917+0000] {standard_task_runner.py:57} INFO - Started process 6690 to run task
[2023-07-11T13:48:17.949+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-06T00:00:00+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpl_9h3gud']
[2023-07-11T13:48:17.960+0000] {standard_task_runner.py:85} INFO - Job 164: Subtask create_file
[2023-07-11T13:48:18.241+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-06T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:48:18.788+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-06T00:00:00+00:00'
[2023-07-11T13:48:18.794+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:48:18.797+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:48:18.850+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:48:18.910+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:48:19.037+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230706T000000, start_date=20230711T134817, end_date=20230711T134819
[2023-07-11T13:48:19.134+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:48:19.214+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:51:16.424+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-06T00:00:00+00:00 [queued]>
[2023-07-11T13:51:16.468+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-06T00:00:00+00:00 [queued]>
[2023-07-11T13:51:16.490+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:51:16.712+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-06 00:00:00+00:00
[2023-07-11T13:51:16.723+0000] {standard_task_runner.py:57} INFO - Started process 6820 to run task
[2023-07-11T13:51:16.792+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-06T00:00:00+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpqsn3gldc']
[2023-07-11T13:51:16.810+0000] {standard_task_runner.py:85} INFO - Job 186: Subtask create_file
[2023-07-11T13:51:17.067+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-06T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:51:17.428+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-06T00:00:00+00:00'
[2023-07-11T13:51:17.431+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:51:17.433+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:51:17.467+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:51:17.535+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:51:17.695+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230706T000000, start_date=20230711T135116, end_date=20230711T135117
[2023-07-11T13:51:17.834+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:51:18.066+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:53:37.738+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-06T00:00:00+00:00 [queued]>
[2023-07-11T13:53:37.816+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-06T00:00:00+00:00 [queued]>
[2023-07-11T13:53:37.837+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:53:37.929+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-06 00:00:00+00:00
[2023-07-11T13:53:37.965+0000] {standard_task_runner.py:57} INFO - Started process 6934 to run task
[2023-07-11T13:53:37.980+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-06T00:00:00+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpem0tqae0']
[2023-07-11T13:53:38.012+0000] {standard_task_runner.py:85} INFO - Job 208: Subtask create_file
[2023-07-11T13:53:38.247+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-06T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:53:38.510+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-06T00:00:00+00:00'
[2023-07-11T13:53:38.516+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:53:38.518+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:53:38.563+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:53:38.603+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:53:38.713+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230706T000000, start_date=20230711T135337, end_date=20230711T135338
[2023-07-11T13:53:38.778+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:53:38.842+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
