[2023-07-11T13:32:01.016+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-05T00:00:00+00:00 [queued]>
[2023-07-11T13:32:01.043+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-05T00:00:00+00:00 [queued]>
[2023-07-11T13:32:01.050+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:32:01.142+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-05 00:00:00+00:00
[2023-07-11T13:32:01.159+0000] {standard_task_runner.py:57} INFO - Started process 6197 to run task
[2023-07-11T13:32:01.176+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-05T00:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmphei0q6qf']
[2023-07-11T13:32:01.183+0000] {standard_task_runner.py:85} INFO - Job 100: Subtask create_file
[2023-07-11T13:32:01.437+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-05T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:32:01.610+0000] {abstractoperator.py:598} ERROR - Exception rendering Jinja template for task 'create_file', field 'bash_command'. Template: '/opt/***/dags/file/mon_script.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/file/mon_script.sh
[2023-07-11T13:32:01.623+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/file/mon_script.sh
[2023-07-11T13:32:01.726+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=exercice_1, task_id=create_file, execution_date=20230705T000000, start_date=20230711T133201, end_date=20230711T133201
[2023-07-11T13:32:01.774+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 100 for task create_file (/opt/airflow/dags/file/mon_script.sh; 6197)
[2023-07-11T13:32:01.809+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-11T13:32:01.886+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:42:01.061+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-05T00:00:00+00:00 [queued]>
[2023-07-11T13:42:01.136+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-05T00:00:00+00:00 [queued]>
[2023-07-11T13:42:01.137+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:42:01.233+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-05 00:00:00+00:00
[2023-07-11T13:42:01.289+0000] {standard_task_runner.py:57} INFO - Started process 6498 to run task
[2023-07-11T13:42:01.301+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-05T00:00:00+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmp5koing2k']
[2023-07-11T13:42:01.327+0000] {standard_task_runner.py:85} INFO - Job 141: Subtask create_file
[2023-07-11T13:42:01.747+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-05T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:42:02.020+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-05T00:00:00+00:00'
[2023-07-11T13:42:02.027+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:42:02.029+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:42:02.103+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:42:02.149+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:42:02.282+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230705T000000, start_date=20230711T134201, end_date=20230711T134202
[2023-07-11T13:42:02.415+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:42:02.505+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:48:16.916+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-05T00:00:00+00:00 [queued]>
[2023-07-11T13:48:17.002+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-05T00:00:00+00:00 [queued]>
[2023-07-11T13:48:17.003+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:48:17.155+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-05 00:00:00+00:00
[2023-07-11T13:48:17.174+0000] {standard_task_runner.py:57} INFO - Started process 6685 to run task
[2023-07-11T13:48:17.204+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-05T00:00:00+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpwlsdz8hi']
[2023-07-11T13:48:17.211+0000] {standard_task_runner.py:85} INFO - Job 163: Subtask create_file
[2023-07-11T13:48:17.492+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-05T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:48:17.880+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-05T00:00:00+00:00'
[2023-07-11T13:48:17.885+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:48:17.901+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:48:18.022+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:48:18.042+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:48:18.233+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230705T000000, start_date=20230711T134816, end_date=20230711T134818
[2023-07-11T13:48:18.406+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:48:18.485+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:51:15.926+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-05T00:00:00+00:00 [queued]>
[2023-07-11T13:51:15.947+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-05T00:00:00+00:00 [queued]>
[2023-07-11T13:51:15.948+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:51:15.993+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-05 00:00:00+00:00
[2023-07-11T13:51:16.009+0000] {standard_task_runner.py:57} INFO - Started process 6811 to run task
[2023-07-11T13:51:16.026+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-05T00:00:00+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpo9jdb5qk']
[2023-07-11T13:51:16.031+0000] {standard_task_runner.py:85} INFO - Job 185: Subtask create_file
[2023-07-11T13:51:16.227+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-05T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:51:16.548+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-05T00:00:00+00:00'
[2023-07-11T13:51:16.554+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:51:16.555+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:51:16.638+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:51:16.752+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:51:16.829+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230705T000000, start_date=20230711T135115, end_date=20230711T135116
[2023-07-11T13:51:16.958+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:51:17.068+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:53:37.233+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-05T00:00:00+00:00 [queued]>
[2023-07-11T13:53:37.261+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-05T00:00:00+00:00 [queued]>
[2023-07-11T13:53:37.262+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:53:37.325+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-05 00:00:00+00:00
[2023-07-11T13:53:37.340+0000] {standard_task_runner.py:57} INFO - Started process 6930 to run task
[2023-07-11T13:53:37.356+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-05T00:00:00+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpqfl2bo7v']
[2023-07-11T13:53:37.362+0000] {standard_task_runner.py:85} INFO - Job 207: Subtask create_file
[2023-07-11T13:53:37.547+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-05T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:53:37.819+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-05T00:00:00+00:00'
[2023-07-11T13:53:37.849+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:53:37.871+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:53:37.927+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:53:38.019+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:53:38.101+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230705T000000, start_date=20230711T135337, end_date=20230711T135338
[2023-07-11T13:53:38.201+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:53:38.266+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
