[2023-07-11T13:32:02.821+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-08T00:00:00+00:00 [queued]>
[2023-07-11T13:32:02.859+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-08T00:00:00+00:00 [queued]>
[2023-07-11T13:32:02.861+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:32:02.909+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-08 00:00:00+00:00
[2023-07-11T13:32:02.920+0000] {standard_task_runner.py:57} INFO - Started process 6203 to run task
[2023-07-11T13:32:02.935+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-08T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpr9ot4zlu']
[2023-07-11T13:32:02.942+0000] {standard_task_runner.py:85} INFO - Job 105: Subtask create_file
[2023-07-11T13:32:03.109+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-08T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:32:03.305+0000] {abstractoperator.py:598} ERROR - Exception rendering Jinja template for task 'create_file', field 'bash_command'. Template: '/opt/***/dags/file/mon_script.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/file/mon_script.sh
[2023-07-11T13:32:03.313+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/file/mon_script.sh
[2023-07-11T13:32:03.338+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=exercice_1, task_id=create_file, execution_date=20230708T000000, start_date=20230711T133202, end_date=20230711T133203
[2023-07-11T13:32:03.393+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 105 for task create_file (/opt/airflow/dags/file/mon_script.sh; 6203)
[2023-07-11T13:32:03.456+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-11T13:32:03.734+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:42:02.949+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-08T00:00:00+00:00 [queued]>
[2023-07-11T13:42:02.979+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-08T00:00:00+00:00 [queued]>
[2023-07-11T13:42:02.985+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:42:03.206+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-08 00:00:00+00:00
[2023-07-11T13:42:03.219+0000] {standard_task_runner.py:57} INFO - Started process 6513 to run task
[2023-07-11T13:42:03.237+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-08T00:00:00+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpplde_ew0']
[2023-07-11T13:42:03.248+0000] {standard_task_runner.py:85} INFO - Job 144: Subtask create_file
[2023-07-11T13:42:03.412+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-08T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:42:03.763+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-08T00:00:00+00:00'
[2023-07-11T13:42:03.774+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:42:03.780+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:42:03.816+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:42:03.880+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:42:03.980+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230708T000000, start_date=20230711T134202, end_date=20230711T134203
[2023-07-11T13:42:04.056+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:42:04.142+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:48:18.712+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-08T00:00:00+00:00 [queued]>
[2023-07-11T13:48:18.748+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-08T00:00:00+00:00 [queued]>
[2023-07-11T13:48:18.751+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:48:18.877+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-08 00:00:00+00:00
[2023-07-11T13:48:18.926+0000] {standard_task_runner.py:57} INFO - Started process 6698 to run task
[2023-07-11T13:48:18.956+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-08T00:00:00+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpymxeyo3l']
[2023-07-11T13:48:18.975+0000] {standard_task_runner.py:85} INFO - Job 166: Subtask create_file
[2023-07-11T13:48:19.263+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-08T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:48:19.766+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-08T00:00:00+00:00'
[2023-07-11T13:48:19.775+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:48:19.777+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:48:19.831+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:48:19.921+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:48:20.052+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230708T000000, start_date=20230711T134818, end_date=20230711T134820
[2023-07-11T13:48:20.166+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:48:20.389+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:51:17.990+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-08T00:00:00+00:00 [queued]>
[2023-07-11T13:51:18.033+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-08T00:00:00+00:00 [queued]>
[2023-07-11T13:51:18.039+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:51:18.091+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-08 00:00:00+00:00
[2023-07-11T13:51:18.101+0000] {standard_task_runner.py:57} INFO - Started process 6831 to run task
[2023-07-11T13:51:18.116+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-08T00:00:00+00:00', '--job-id', '188', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpyh9rb8ul']
[2023-07-11T13:51:18.144+0000] {standard_task_runner.py:85} INFO - Job 188: Subtask create_file
[2023-07-11T13:51:18.344+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-08T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:51:18.670+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-08T00:00:00+00:00'
[2023-07-11T13:51:18.677+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:51:18.681+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:51:18.702+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:51:18.729+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:51:18.781+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230708T000000, start_date=20230711T135118, end_date=20230711T135118
[2023-07-11T13:51:18.828+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:51:18.915+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:53:38.782+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-08T00:00:00+00:00 [queued]>
[2023-07-11T13:53:38.819+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-08T00:00:00+00:00 [queued]>
[2023-07-11T13:53:38.828+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:53:38.884+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-08 00:00:00+00:00
[2023-07-11T13:53:38.902+0000] {standard_task_runner.py:57} INFO - Started process 6945 to run task
[2023-07-11T13:53:38.932+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-08T00:00:00+00:00', '--job-id', '210', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpn2t4z4xh']
[2023-07-11T13:53:38.945+0000] {standard_task_runner.py:85} INFO - Job 210: Subtask create_file
[2023-07-11T13:53:39.166+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-08T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:53:39.543+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-08T00:00:00+00:00'
[2023-07-11T13:53:39.549+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:53:39.561+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:53:39.597+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:53:39.656+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:53:39.721+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230708T000000, start_date=20230711T135338, end_date=20230711T135339
[2023-07-11T13:53:39.992+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:53:40.094+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
