[2023-07-11T13:32:00.624+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-03T00:00:00+00:00 [queued]>
[2023-07-11T13:32:00.645+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-03T00:00:00+00:00 [queued]>
[2023-07-11T13:32:00.653+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:32:00.799+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-03 00:00:00+00:00
[2023-07-11T13:32:00.814+0000] {standard_task_runner.py:57} INFO - Started process 6196 to run task
[2023-07-11T13:32:00.826+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-03T00:00:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpd7rgo5i0']
[2023-07-11T13:32:00.834+0000] {standard_task_runner.py:85} INFO - Job 99: Subtask create_file
[2023-07-11T13:32:01.014+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-03T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:32:01.182+0000] {abstractoperator.py:598} ERROR - Exception rendering Jinja template for task 'create_file', field 'bash_command'. Template: '/opt/***/dags/file/mon_script.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/file/mon_script.sh
[2023-07-11T13:32:01.185+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/file/mon_script.sh
[2023-07-11T13:32:01.215+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=exercice_1, task_id=create_file, execution_date=20230703T000000, start_date=20230711T133200, end_date=20230711T133201
[2023-07-11T13:32:01.253+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 99 for task create_file (/opt/airflow/dags/file/mon_script.sh; 6196)
[2023-07-11T13:32:01.289+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-11T13:32:01.440+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:42:00.287+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-03T00:00:00+00:00 [queued]>
[2023-07-11T13:42:00.317+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-03T00:00:00+00:00 [queued]>
[2023-07-11T13:42:00.325+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:42:00.476+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-03 00:00:00+00:00
[2023-07-11T13:42:00.521+0000] {standard_task_runner.py:57} INFO - Started process 6489 to run task
[2023-07-11T13:42:00.541+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-03T00:00:00+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpdq8abice']
[2023-07-11T13:42:00.548+0000] {standard_task_runner.py:85} INFO - Job 138: Subtask create_file
[2023-07-11T13:42:00.765+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-03T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:42:00.992+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-03T00:00:00+00:00'
[2023-07-11T13:42:01.006+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:42:01.013+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:42:01.046+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:42:01.081+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:42:01.177+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230703T000000, start_date=20230711T134200, end_date=20230711T134201
[2023-07-11T13:42:01.340+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:42:01.542+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:48:15.734+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-03T00:00:00+00:00 [queued]>
[2023-07-11T13:48:15.764+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-03T00:00:00+00:00 [queued]>
[2023-07-11T13:48:15.777+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:48:15.885+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-03 00:00:00+00:00
[2023-07-11T13:48:15.894+0000] {standard_task_runner.py:57} INFO - Started process 6676 to run task
[2023-07-11T13:48:15.911+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-03T00:00:00+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmppul0ed3j']
[2023-07-11T13:48:15.932+0000] {standard_task_runner.py:85} INFO - Job 161: Subtask create_file
[2023-07-11T13:48:16.241+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-03T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:48:16.752+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-03T00:00:00+00:00'
[2023-07-11T13:48:16.765+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:48:16.769+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:48:16.803+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:48:16.862+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:48:17.018+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230703T000000, start_date=20230711T134815, end_date=20230711T134817
[2023-07-11T13:48:17.232+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:48:17.351+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:51:15.090+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-03T00:00:00+00:00 [queued]>
[2023-07-11T13:51:15.125+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-03T00:00:00+00:00 [queued]>
[2023-07-11T13:51:15.133+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:51:15.324+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-03 00:00:00+00:00
[2023-07-11T13:51:15.338+0000] {standard_task_runner.py:57} INFO - Started process 6799 to run task
[2023-07-11T13:51:15.357+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-03T00:00:00+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmp95mpo1x8']
[2023-07-11T13:51:15.384+0000] {standard_task_runner.py:85} INFO - Job 183: Subtask create_file
[2023-07-11T13:51:15.663+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-03T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:51:16.047+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-03T00:00:00+00:00'
[2023-07-11T13:51:16.052+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:51:16.054+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:51:16.126+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:51:16.224+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:51:16.355+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230703T000000, start_date=20230711T135115, end_date=20230711T135116
[2023-07-11T13:51:16.427+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:51:16.763+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:53:36.272+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-03T00:00:00+00:00 [queued]>
[2023-07-11T13:53:36.295+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-03T00:00:00+00:00 [queued]>
[2023-07-11T13:53:36.296+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:53:36.337+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-03 00:00:00+00:00
[2023-07-11T13:53:36.351+0000] {standard_task_runner.py:57} INFO - Started process 6920 to run task
[2023-07-11T13:53:36.374+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-03T00:00:00+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmp22403id9']
[2023-07-11T13:53:36.384+0000] {standard_task_runner.py:85} INFO - Job 205: Subtask create_file
[2023-07-11T13:53:36.545+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-03T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:53:36.895+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-03T00:00:00+00:00'
[2023-07-11T13:53:36.917+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:53:36.928+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:53:36.979+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:53:37.003+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:53:37.081+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230703T000000, start_date=20230711T135336, end_date=20230711T135337
[2023-07-11T13:53:37.169+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:53:37.236+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
