[2023-07-11T13:32:02.340+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-07T00:00:00+00:00 [queued]>
[2023-07-11T13:32:02.360+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-07T00:00:00+00:00 [queued]>
[2023-07-11T13:32:02.361+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:32:02.400+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-07 00:00:00+00:00
[2023-07-11T13:32:02.410+0000] {standard_task_runner.py:57} INFO - Started process 6202 to run task
[2023-07-11T13:32:02.418+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-07T00:00:00+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpkhrg7s9c']
[2023-07-11T13:32:02.423+0000] {standard_task_runner.py:85} INFO - Job 104: Subtask create_file
[2023-07-11T13:32:02.557+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-07T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:32:02.690+0000] {abstractoperator.py:598} ERROR - Exception rendering Jinja template for task 'create_file', field 'bash_command'. Template: '/opt/***/dags/file/mon_script.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/file/mon_script.sh
[2023-07-11T13:32:02.696+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/file/mon_script.sh
[2023-07-11T13:32:02.722+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=exercice_1, task_id=create_file, execution_date=20230707T000000, start_date=20230711T133202, end_date=20230711T133202
[2023-07-11T13:32:02.785+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 104 for task create_file (/opt/airflow/dags/file/mon_script.sh; 6202)
[2023-07-11T13:32:02.851+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-11T13:32:02.917+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:42:02.191+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-07T00:00:00+00:00 [queued]>
[2023-07-11T13:42:02.248+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-07T00:00:00+00:00 [queued]>
[2023-07-11T13:42:02.250+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:42:02.385+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-07 00:00:00+00:00
[2023-07-11T13:42:02.399+0000] {standard_task_runner.py:57} INFO - Started process 6507 to run task
[2023-07-11T13:42:02.417+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-07T00:00:00+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpkp9x30zp']
[2023-07-11T13:42:02.457+0000] {standard_task_runner.py:85} INFO - Job 143: Subtask create_file
[2023-07-11T13:42:02.747+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-07T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:42:03.133+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-07T00:00:00+00:00'
[2023-07-11T13:42:03.142+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:42:03.147+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:42:03.182+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:42:03.265+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:42:03.416+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230707T000000, start_date=20230711T134202, end_date=20230711T134203
[2023-07-11T13:42:03.551+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:42:03.655+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:48:18.327+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-07T00:00:00+00:00 [queued]>
[2023-07-11T13:48:18.363+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-07T00:00:00+00:00 [queued]>
[2023-07-11T13:48:18.373+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:48:18.464+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-07 00:00:00+00:00
[2023-07-11T13:48:18.475+0000] {standard_task_runner.py:57} INFO - Started process 6695 to run task
[2023-07-11T13:48:18.495+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-07T00:00:00+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpvvio9bq9']
[2023-07-11T13:48:18.511+0000] {standard_task_runner.py:85} INFO - Job 165: Subtask create_file
[2023-07-11T13:48:18.779+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-07T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:48:19.065+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-07T00:00:00+00:00'
[2023-07-11T13:48:19.069+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:48:19.071+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:48:19.154+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:48:19.196+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:48:19.317+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230707T000000, start_date=20230711T134818, end_date=20230711T134819
[2023-07-11T13:48:19.525+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:48:19.595+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:51:17.382+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-07T00:00:00+00:00 [queued]>
[2023-07-11T13:51:17.408+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-07T00:00:00+00:00 [queued]>
[2023-07-11T13:51:17.409+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:51:17.493+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-07 00:00:00+00:00
[2023-07-11T13:51:17.509+0000] {standard_task_runner.py:57} INFO - Started process 6828 to run task
[2023-07-11T13:51:17.547+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-07T00:00:00+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpzqkqfu3g']
[2023-07-11T13:51:17.552+0000] {standard_task_runner.py:85} INFO - Job 187: Subtask create_file
[2023-07-11T13:51:17.866+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-07T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:51:18.144+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-07T00:00:00+00:00'
[2023-07-11T13:51:18.159+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:51:18.169+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:51:18.225+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:51:18.366+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:51:18.436+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230707T000000, start_date=20230711T135117, end_date=20230711T135118
[2023-07-11T13:51:18.555+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:51:18.641+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:53:38.213+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-07T00:00:00+00:00 [queued]>
[2023-07-11T13:53:38.244+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-07T00:00:00+00:00 [queued]>
[2023-07-11T13:53:38.247+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:53:38.303+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-07 00:00:00+00:00
[2023-07-11T13:53:38.312+0000] {standard_task_runner.py:57} INFO - Started process 6938 to run task
[2023-07-11T13:53:38.335+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-07T00:00:00+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmp7mtwnuos']
[2023-07-11T13:53:38.357+0000] {standard_task_runner.py:85} INFO - Job 209: Subtask create_file
[2023-07-11T13:53:38.511+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-07T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:53:38.737+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-07T00:00:00+00:00'
[2023-07-11T13:53:38.742+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:53:38.749+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:53:38.829+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:53:38.884+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:53:39.010+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230707T000000, start_date=20230711T135338, end_date=20230711T135339
[2023-07-11T13:53:39.098+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:53:39.163+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
