[2023-07-11T13:32:03.442+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-09T00:00:00+00:00 [queued]>
[2023-07-11T13:32:03.493+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-09T00:00:00+00:00 [queued]>
[2023-07-11T13:32:03.498+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:32:03.691+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-09 00:00:00+00:00
[2023-07-11T13:32:03.700+0000] {standard_task_runner.py:57} INFO - Started process 6204 to run task
[2023-07-11T13:32:03.707+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-09T00:00:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmp_vxrlakq']
[2023-07-11T13:32:03.715+0000] {standard_task_runner.py:85} INFO - Job 106: Subtask create_file
[2023-07-11T13:32:03.828+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-09T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:32:03.904+0000] {abstractoperator.py:598} ERROR - Exception rendering Jinja template for task 'create_file', field 'bash_command'. Template: '/opt/***/dags/file/mon_script.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/file/mon_script.sh
[2023-07-11T13:32:03.907+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/file/mon_script.sh
[2023-07-11T13:32:03.922+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=exercice_1, task_id=create_file, execution_date=20230709T000000, start_date=20230711T133203, end_date=20230711T133203
[2023-07-11T13:32:03.947+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 106 for task create_file (/opt/airflow/dags/file/mon_script.sh; 6204)
[2023-07-11T13:32:03.999+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-11T13:32:04.049+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:42:03.180+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-09T00:00:00+00:00 [queued]>
[2023-07-11T13:42:03.211+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-09T00:00:00+00:00 [queued]>
[2023-07-11T13:42:03.224+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:42:03.283+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-09 00:00:00+00:00
[2023-07-11T13:42:03.314+0000] {standard_task_runner.py:57} INFO - Started process 6515 to run task
[2023-07-11T13:42:03.313+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-09T00:00:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpu4yh2cu0']
[2023-07-11T13:42:03.319+0000] {standard_task_runner.py:85} INFO - Job 145: Subtask create_file
[2023-07-11T13:42:03.528+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-09T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:42:03.892+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-09T00:00:00+00:00'
[2023-07-11T13:42:03.899+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:42:03.901+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:42:03.934+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:42:03.974+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:42:04.140+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230709T000000, start_date=20230711T134203, end_date=20230711T134204
[2023-07-11T13:42:04.253+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:42:04.325+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:48:19.444+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-09T00:00:00+00:00 [queued]>
[2023-07-11T13:48:19.465+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-09T00:00:00+00:00 [queued]>
[2023-07-11T13:48:19.468+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:48:19.607+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-09 00:00:00+00:00
[2023-07-11T13:48:19.617+0000] {standard_task_runner.py:57} INFO - Started process 6702 to run task
[2023-07-11T13:48:19.626+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-09T00:00:00+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpe9a5xs3g']
[2023-07-11T13:48:19.631+0000] {standard_task_runner.py:85} INFO - Job 167: Subtask create_file
[2023-07-11T13:48:19.845+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-09T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:48:20.223+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-09T00:00:00+00:00'
[2023-07-11T13:48:20.228+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:48:20.231+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:48:20.263+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:48:20.323+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:48:20.392+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230709T000000, start_date=20230711T134819, end_date=20230711T134820
[2023-07-11T13:48:20.493+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:48:20.578+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:51:18.404+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-09T00:00:00+00:00 [queued]>
[2023-07-11T13:51:18.451+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-09T00:00:00+00:00 [queued]>
[2023-07-11T13:51:18.452+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:51:18.523+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-09 00:00:00+00:00
[2023-07-11T13:51:18.535+0000] {standard_task_runner.py:57} INFO - Started process 6835 to run task
[2023-07-11T13:51:18.556+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-09T00:00:00+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpz1o20tes']
[2023-07-11T13:51:18.584+0000] {standard_task_runner.py:85} INFO - Job 189: Subtask create_file
[2023-07-11T13:51:18.792+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-09T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:51:19.126+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-09T00:00:00+00:00'
[2023-07-11T13:51:19.132+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:51:19.134+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:51:19.165+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:51:19.212+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:51:19.272+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230709T000000, start_date=20230711T135118, end_date=20230711T135119
[2023-07-11T13:51:19.331+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:51:19.381+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:53:39.075+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-09T00:00:00+00:00 [queued]>
[2023-07-11T13:53:39.116+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-09T00:00:00+00:00 [queued]>
[2023-07-11T13:53:39.126+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:53:39.199+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-09 00:00:00+00:00
[2023-07-11T13:53:39.208+0000] {standard_task_runner.py:57} INFO - Started process 6947 to run task
[2023-07-11T13:53:39.241+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-09T00:00:00+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmp6y0xb4bp']
[2023-07-11T13:53:39.265+0000] {standard_task_runner.py:85} INFO - Job 211: Subtask create_file
[2023-07-11T13:53:39.501+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-09T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:53:39.773+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-09T00:00:00+00:00'
[2023-07-11T13:53:39.780+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:53:39.782+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:53:39.822+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:53:39.872+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:53:39.990+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230709T000000, start_date=20230711T135339, end_date=20230711T135339
[2023-07-11T13:53:40.074+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:53:40.180+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
