[2023-07-11T13:32:00.521+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-02T00:00:00+00:00 [queued]>
[2023-07-11T13:32:00.581+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-02T00:00:00+00:00 [queued]>
[2023-07-11T13:32:00.582+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:32:00.798+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-02 00:00:00+00:00
[2023-07-11T13:32:00.808+0000] {standard_task_runner.py:57} INFO - Started process 6195 to run task
[2023-07-11T13:32:00.832+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-02T00:00:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpr7q4v6w7']
[2023-07-11T13:32:00.852+0000] {standard_task_runner.py:85} INFO - Job 102: Subtask create_file
[2023-07-11T13:32:01.163+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-02T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:32:01.329+0000] {abstractoperator.py:598} ERROR - Exception rendering Jinja template for task 'create_file', field 'bash_command'. Template: '/opt/***/dags/file/mon_script.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/file/mon_script.sh
[2023-07-11T13:32:01.335+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/file/mon_script.sh
[2023-07-11T13:32:01.357+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=exercice_1, task_id=create_file, execution_date=20230702T000000, start_date=20230711T133200, end_date=20230711T133201
[2023-07-11T13:32:01.423+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 102 for task create_file (/opt/airflow/dags/file/mon_script.sh; 6195)
[2023-07-11T13:32:01.505+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-11T13:32:01.616+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:42:00.019+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-02T00:00:00+00:00 [queued]>
[2023-07-11T13:42:00.068+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-02T00:00:00+00:00 [queued]>
[2023-07-11T13:42:00.071+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:42:00.131+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-02 00:00:00+00:00
[2023-07-11T13:42:00.150+0000] {standard_task_runner.py:57} INFO - Started process 6485 to run task
[2023-07-11T13:42:00.176+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-02T00:00:00+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpyiei9ehy']
[2023-07-11T13:42:00.182+0000] {standard_task_runner.py:85} INFO - Job 139: Subtask create_file
[2023-07-11T13:42:00.420+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-02T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:42:00.709+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-02T00:00:00+00:00'
[2023-07-11T13:42:00.716+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:42:00.719+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:42:00.751+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:42:00.801+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:42:00.887+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230702T000000, start_date=20230711T134200, end_date=20230711T134200
[2023-07-11T13:42:00.966+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:42:01.030+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:48:15.221+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-02T00:00:00+00:00 [queued]>
[2023-07-11T13:48:15.242+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-02T00:00:00+00:00 [queued]>
[2023-07-11T13:48:15.246+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:48:15.346+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-02 00:00:00+00:00
[2023-07-11T13:48:15.358+0000] {standard_task_runner.py:57} INFO - Started process 6671 to run task
[2023-07-11T13:48:15.364+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-02T00:00:00+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpfs_k3a1_']
[2023-07-11T13:48:15.369+0000] {standard_task_runner.py:85} INFO - Job 160: Subtask create_file
[2023-07-11T13:48:15.709+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-02T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:48:16.143+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-02T00:00:00+00:00'
[2023-07-11T13:48:16.150+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:48:16.152+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:48:16.223+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:48:16.308+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:48:16.466+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230702T000000, start_date=20230711T134815, end_date=20230711T134816
[2023-07-11T13:48:16.674+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:48:16.852+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:51:14.576+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-02T00:00:00+00:00 [queued]>
[2023-07-11T13:51:14.601+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-02T00:00:00+00:00 [queued]>
[2023-07-11T13:51:14.602+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:51:14.786+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-02 00:00:00+00:00
[2023-07-11T13:51:14.805+0000] {standard_task_runner.py:57} INFO - Started process 6795 to run task
[2023-07-11T13:51:14.828+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-02T00:00:00+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmprrnpz6wx']
[2023-07-11T13:51:14.845+0000] {standard_task_runner.py:85} INFO - Job 182: Subtask create_file
[2023-07-11T13:51:15.045+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-02T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:51:15.386+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-02T00:00:00+00:00'
[2023-07-11T13:51:15.402+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:51:15.404+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:51:15.480+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:51:15.580+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:51:15.705+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230702T000000, start_date=20230711T135114, end_date=20230711T135115
[2023-07-11T13:51:15.825+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:51:16.003+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-11T13:53:35.902+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-02T00:00:00+00:00 [queued]>
[2023-07-11T13:53:35.922+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercice_1.create_file scheduled__2023-07-02T00:00:00+00:00 [queued]>
[2023-07-11T13:53:35.923+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-11T13:53:36.116+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_file> on 2023-07-02 00:00:00+00:00
[2023-07-11T13:53:36.129+0000] {standard_task_runner.py:57} INFO - Started process 6916 to run task
[2023-07-11T13:53:36.157+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercice_1', 'create_file', 'scheduled__2023-07-02T00:00:00+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/correction.py', '--cfg-path', '/tmp/tmpkps2q8vz']
[2023-07-11T13:53:36.178+0000] {standard_task_runner.py:85} INFO - Job 204: Subtask create_file
[2023-07-11T13:53:36.382+0000] {task_command.py:410} INFO - Running <TaskInstance: exercice_1.create_file scheduled__2023-07-02T00:00:00+00:00 [running]> on host 1d6232dcfa4d
[2023-07-11T13:53:36.699+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercice_1' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2023-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-02T00:00:00+00:00'
[2023-07-11T13:53:36.709+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-11T13:53:36.713+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/dags/file/mon_script.sh ']
[2023-07-11T13:53:36.771+0000] {subprocess.py:86} INFO - Output:
[2023-07-11T13:53:36.849+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-11T13:53:36.944+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=exercice_1, task_id=create_file, execution_date=20230702T000000, start_date=20230711T135335, end_date=20230711T135336
[2023-07-11T13:53:37.111+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-11T13:53:37.189+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
